### ISSUE TITLE
Problems with AWS Keyspaces

### ISSUE THREAD

**Issue by vittoriocanilli** [datastax/cql-proxy#100]
Hello,

I have a PHP third-party application, which needs to access a Cassandra keyspace and it does not support TLS connections; I have set up a Cassandra keyspace in AWS Keyspaces, which requires TLS connections: therefore I am trying to use this proxy.

After that I have followed these [instructions](https://docs.aws.amazon.com/keyspaces/latest/devguide/programmatic.cqlsh.html), I managed successfully to connect to my Cassandra keyspace on AWS Keyspaces locally via `cqlsh`.

Before configuring your proxy in a Kubernetes container (where the PHP third-party application is running), I am trying to run the `cql-proxy` image for some local tests:

```shell script
docker run -p 9042:9042 \
  --rm datastax/cql-proxy:v0.1.3 \
  --contact-points="cassandra.eu-west-1.amazonaws.com" --username="${CASSANDRA_USERNAME}" \
  --password="${CASSANDRA_PASSWORD}" --port="9142" --bind="127.0.0.1:9042" \
  --proxy-cert-file="/path/to/sf-class2-root.crt" --debug
```

Unfortunately this simply returns the following error without further explanation:

```shell script
cql-proxy: error: unable to connect to cluster context deadline exceeded
```

Am I missing something in the parameters passed for my test? Has somebody else tested this proxy solution  with  AWS Keyspaces already? Thanks in advance.

**Comment by mpenick** [comment]
cql-proxy doesn't currently support  Proxy <--> Cassandra TLS. It only supports Client <--> Proxy and Proxy <--> Astra TLS. PRs welcome.

**Comment by kamek-pf** [comment]
@vittoriocanilli I'm in a similar situation, did you find a solution ?

**Comment by mpenick** [comment]
Here's a PR that support Proxy <--> Cassandra TLS: https://github.com/datastax/cql-proxy/pull/103. It's not tested yet, but please give it a try!

**Comment by vittoriocanilli** [comment]
@kamek-pf sorry for the very late reply; eventually I have managed to achieve my goal by using a container with HAProxy instead of CqlProxy.
