### ISSUE TITLE
feature request , add SSL wire encryption to port 9042 started by cql-proxy 

### ISSUE THREAD

**Issue by pidiaquez** [datastax/cql-proxy#108]
would it be possible to enable wire encryption / SSL to port 9042 started by cql-proxy 
any possible workarounds to enable this ?

**Comment by absurdfarce** [comment]
@pidiaquez Does providing --proxy-key-file and --proxy-cert-file not meet your needs?  See the ["Configuration" section of the README](https://github.com/datastax/cql-proxy#configuration) for more on this.
