### ISSUE TITLE
Exception thrown when the Host mapping contains a nil host.

### ISSUE THREAD

**Issue by PatrickCallaghan** [datastax/cql-proxy#43]
Exception when the Host mapping contains a nil host. This issue is created from a customer request who is looking at using the Go Driver.

**Comment by gcatalog** [comment]
looks like it's coming from this code snippet 
```
	sniProxyAddress, err := r.getSNIProxyAddress()
	if err != nil {
		return nil, err
	}
	hostId, err := row.ByName("host_id")
	if err != nil {
		return nil, err
	}
	uuid := hostId.(primitive.UUID)
```

**Comment by mpenick** [comment]
@gcatalog Working on a fix.

**Comment by gcatalog** [comment]
@mpenick I see the changes were merged which is great, do you know when you expect to have a new release/image available?

**Comment by mpenick** [comment]
Working on getting `v0.0.3` out later today. It looks like I need to fix a issue with the test on arm64.

**Comment by mpenick** [comment]
@gcatalog `v0.0.3` released.

Tag: https://github.com/datastax/cql-proxy/releases/tag/v0.0.3

Docker image: https://hub.docker.com/layers/175487408/datastax/cql-proxy/v0.0.3/images/sha256-46137053d54b659e587f08cf2ea617f46bacf5f2aebea8309c342cf9a455643c?context=repo
