### ISSUE TITLE
Connection Closed: Unable to decode header

### ISSUE THREAD

**Issue by datalatics-official** [datastax/cql-proxy#49]
When try to make connection with proxy service. It logs a message that "unable to decode hearder" and close the connection. Need to fix is soon. Please find the attach error's screenshot. 
![astra_connection_error](https://user-images.githubusercontent.com/95012419/143429225-2b40ed93-9fc5-4660-80d2-5be0e6a7c2dc.png)

When we try to run it with --debug.
![image](https://user-images.githubusercontent.com/95012419/143535859-29f1f2e9-26b7-4b44-9407-66bc728ba378.png)

@mpenick

**Comment by mpenick** [comment]
What driver and its version is connecting to proxy?

**Comment by mpenick** [comment]
It looks like you might be using java-driver `2.1.X`. This isn't currently supported for a couple reasons:

1) This is the easier problem to solve. The `2.X` driver using the CQL protocol v3, and cql-proxy currently hard codes the version to v4.  This small patch fixes that issue: 

```diff
diff --git a/proxy.go b/proxy.go
index 5af2412..b7b073c 100644
--- a/proxy.go
+++ b/proxy.go
@@ -83,7 +83,7 @@ func main() {
 	}
 
 	p := proxy.NewProxy(ctx, proxy.Config{
-		Version:           primitive.ProtocolVersion4,
+		Version:           primitive.ProtocolVersion3,
 		Resolver:          resolver,
 		ReconnectPolicy:   proxycore.NewReconnectPolicy(),
 		NumConns:          1,
```

However, this is not an actual fix though. My thought is the proxy should allow clients to be connected to the backend using multiple protocol versions simultaneously. It could have a session cache for each version.

2) The bigger problem is Astra doesn't not support the legacy schema tables that used to live under `system`. It's possible that the proxy could intercept these calls and do some type of conversion to/from the new schema tables under `system_schema`. This could be a lot of work, but maybe only a subset needs to be supported to get older drivers working properly.

**Comment by mpenick** [comment]
I've created issues to track handling these two issues:

1) https://github.com/datastax/cql-proxy/issues/7
2) https://github.com/datastax/cql-proxy/issues/51

**Comment by mpenick** [comment]
This fixes both issues: https://github.com/datastax/cql-proxy/pull/52

**Comment by datalatics-official** [comment]
> What driver and its version is connecting to the proxy?

"com.datastax.cassandra" % "cassandra-driver-core" % "2.1.10.3"

**Comment by mpenick** [comment]
Released https://github.com/datastax/cql-proxy/releases/tag/v0.0.4. Let me know if this fixes your issue.

**Comment by datalatics-official** [comment]
Thank you @mpenick
