### ISSUE TITLE
"describe" command doesnt display results

### ISSUE THREAD

**Issue by melienherrera** [datastax/cql-proxy#61]
`describe keyspaces` and `describe tables` both return blank when I run it in cqlsh.

`Connected to cql-proxy at 127.0.0.1:9042
[cqlsh 6.0.0 | Cassandra 4.0.0.6816 | CQL spec 3.4.5 | Native protocol v4]`
![Screen Shot 2021-12-20 at 11 00 37 AM](https://user-images.githubusercontent.com/85907755/146818872-faa80aca-039c-4d2e-b4c2-4a2ba760b500.png)
 
I am able to retrieve results on the Astra UI using cql-proxy as well as just using the secure connect bundle, but not when I connect with the proxy.

**Comment by mpenick** [comment]
I'm unable to reproduce the issue:

```
$ cqlsh
Connected to cql-proxy at 127.0.0.1:9042.
[cqlsh 6.8.0 | Cassandra 4.0.0.6816 | CQL spec 3.4.5 | Native protocol v4]
Use HELP for help.
cqlsh> use sketch ;
cqlsh:sketch> DESCRIBE KEYSPACES ;

system_virtual_schema  system_auth   sketch  datastax_sla        system_traces
system_schema          system_views  system  data_endpoint_auth

cqlsh:sketch> DESCRIBE TABLES ;

sketches  players  game  votes  answers

cqlsh:sketch> 
```

**Comment by mpenick** [comment]
I see you're using cqlsh 6.0.0. Maybe that's the issue?  Where did you install that from (so I can reproduce)?

**Comment by mpenick** [comment]
I see. This is not cql-proxy issue. C* 4.0 added server-side describe: https://issues.apache.org/jira/browse/CASSANDRA-8005 which is not supported by Astra currently.  

Before `cqlsh` handled the `DESCRIBE` operations by querying the schema tables (keyspace: `system_schema`), but now the server-side can handle `DESCRIBE` operations, but Astra doesn't.

The proxy is just forwarding the query to the server-side:

```
2021-12-21T09:12:28.874-0500	DEBUG	proxy/proxy.go:416	handling query	{"query": "DESCRIBE TABLES ;", "stream": 3}
2021-12-21T09:12:30.485-0500	DEBUG	proxy/proxy.go:416	handling query	{"query": "DESCRIBE TABLES ;", "stream": 4}
```

**Comment by mpenick** [comment]
If you connect to Astra directly by unzip your secure connect bundle you'll run into the same issue:

```
unzip secure-connect-bundle.zip -d secure-connect-bundle
cd secure-connect-bundle
/path/to/cqlsh --cqlshrc cqlshrc -u <username> -p <password>
```

**Comment by melienherrera** [comment]
> ~I see you're using cqlsh 6.0.0. Maybe that's the issue? Where did you install that from (so I can reproduce)?~
> 
> Never mind. I see that's the version included with C* 4.0.

Hi there, thanks for all of the info!

So if I use cqlsh 6.8.0 would the `DESCRIBE` command display properly? In that first example where you tried to reproduce the issue, that was through `cql-proxy` right?

**Comment by mpenick** [comment]
> > ~I see you're using cqlsh 6.0.0. Maybe that's the issue? Where did you install that from (so I can reproduce)?~
> > Never mind. I see that's the version included with C* 4.0.
> 
> Hi there, thanks for all of the info!
> 
> So if I use cqlsh 6.8.0 would the `DESCRIBE` command display properly? In that first example where you tried to reproduce the issue, that was through `cql-proxy` right?

Correct, cqlsh 6.8.0 works properly as it's not using server-side DESCRIBE. 

Yes, the first example is using cql-proxy.

**Comment by melienherrera** [comment]
Interesting, I am having a hard time getting cqlsh 6.8.0 with cql-proxy, any thoughts?

**Comment by melienherrera** [comment]
@dougwettlaufer when I would run the `describe` command, it would basically show nothing. I noticed the difference between my cqlsh and yours is that for some reason, mine is pulling `cqlsh 6.0.0` instead of `cqlsh 6.8.0` and I cant seem to figure out why

**Comment by dougwettlaufer** [comment]
And you downloaded 6.8 from [here](https://downloads.datastax.com/#cqlsh) (the dropdown might default to Astra so you'll want to make sure it says "DataStax Enterprise 6.8")? If you run cql-proxy with `--debug` you can see what queries are being sent from cqlsh.

**Comment by melienherrera** [comment]
Thanks - had to cd into the bin file and then run `./cqlsh` 

I appreciate the help. I'll close this issue now.
